const models=[
{title:'Mortise & Tenon Joint',short:'Mortise & Tenon',img:'images/mortise.png',glb:'models/mortise_step1.glb',desc:'Sambungan lidah dan lubang yang kuat dan stabil, sesuai untuk struktur rangka dan perabot tahan lama.',learn:'Memahami struktur lidah dan lubang serta fungsinya.',apply:'Perabot, rangka pintu, tingkap dan struktur binaan.',adv:'Kukuh, stabil dan tahan lama.'},
{title:'Dovetail Joint',short:'Dovetail Joint',img:'images/dovetail.png',glb:'models/dovetail_step1.glb',desc:'Tanggam berbentuk ekor merpati yang terkenal dengan kekuatan tarikan dan nilai estetika.',learn:'Mengenal pasti bentuk kunci dovetail.',apply:'Laci, kotak kayu dan kabinet.',adv:'Kuat, kemas dan menarik.'},
{title:'Box Joint',short:'Box Joint',img:'images/box.png',glb:'models/box_step1.glb',desc:'Sambungan jejari berselang-seli yang menghasilkan kawasan lekatan luas.',learn:'Memahami sambungan jejari berselang.',apply:'Kotak, laci dan panel.',adv:'Mudah dibuat dan kuat.'},
{title:'Lap Joint',short:'Lap Joint',img:'images/lap.png',glb:'models/lap_step1.glb',desc:'Dua komponen kayu bertindih separuh untuk membentuk sambungan rata.',learn:'Memahami konsep pertindihan separuh kayu.',apply:'Rangka, bingkai dan struktur ringan.',adv:'Ringkas, cepat dan stabil.'},
{title:'Finger Joint',short:'Finger Joint',img:'images/tounge.png',glb:'models/tongue_step1.glb',desc:'Sambungan jejari halus yang meningkatkan kawasan gam dan kekuatan kayu.',learn:'Mengenal bentuk jejari dan arah cantuman.',apply:'Penyambungan kayu panjang dan panel.',adv:'Menjimatkan bahan dan kukuh.'},
{title:'Mitre Joint',short:'Mitre Joint',img:'images/miter.png',glb:'models/miter_step1.glb',desc:'Sambungan sudut 45 darjah yang memberi kemasan bersih dan profesional.',learn:'Memahami sudut potongan mitre.',apply:'Bingkai gambar, trim dan perabot hiasan.',adv:'Kemas dan estetik.'},
{title:'Three-Way Cross Joint',short:'Three-Way Cross Joint',img:'images/cross.png',glb:'models/cross_step1.glb',desc:'Sambungan tiga arah yang menunjukkan hubungan spatial kayu secara kompleks.',learn:'Memahami penyambungan tiga arah dalam ruang 3D.',apply:'Struktur kreatif dan latihan visualisasi spatial.',adv:'Meningkatkan kefahaman ruang.'}
];
document.querySelector('.menuBtn')?.addEventListener('click',()=>document.querySelector('.links').classList.toggle('open'));
const strip=document.getElementById('modelStrip');if(strip){models.forEach((m,i)=>strip.innerHTML+=`<article><img src="${m.img}" alt="${m.short}"><small>0${i+1}</small><b>${m.short}</b></article>`)}
const list=document.getElementById('modelList'),viewer=document.getElementById('viewer');function setModel(i){const m=models[i]; if(!viewer)return; viewer.src=m.glb; document.getElementById('modelTitle').textContent=m.title; document.getElementById('modelDesc').textContent=m.desc; document.getElementById('learn').textContent=m.learn; document.getElementById('apply').textContent=m.apply; document.getElementById('adv').textContent=m.adv; [...document.querySelectorAll('#modelList button')].forEach((b,x)=>b.classList.toggle('active',x===i)); const t=document.getElementById('thumbs'); t.innerHTML=''; models.forEach(x=>t.innerHTML+=`<img src="${x.img}" alt="${x.short}">`)}
if(list){models.forEach((m,i)=>{let b=document.createElement('button');b.textContent=`0${i+1}  ${m.short}`;b.onclick=()=>setModel(i);list.appendChild(b)});setModel(0);document.getElementById('autoRotate').addEventListener('change',e=>{e.target.checked?viewer.setAttribute('auto-rotate',''):viewer.removeAttribute('auto-rotate')})}
