function toggleMenu(){document.getElementById('navLinks')?.classList.toggle('open')}
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const modelData={
 mortise:{title:'Mortise & Tenon Joint',base:'mortise',desc:'Sambungan lidah dan lubang yang kuat dan stabil, sesuai untuk struktur rangka dan perabot tahan lama.',outcome:'Memahami struktur lidah dan lubang serta fungsinya.',app:'Perabot, rangka pintu, tingkap dan struktur binaan.',adv:'Kukuh, stabil dan tahan lama.'},
 dovetail:{title:'Dovetail Joint',base:'dovetail',desc:'Sambungan berbentuk ekor merpati yang mengunci dua komponen kayu dengan kemas.',outcome:'Mengenal pasti bentuk serong dan fungsi kuncian dovetail.',app:'Laci, kotak kayu dan perabot berkualiti.',adv:'Kuat, kemas dan mempunyai nilai estetika tinggi.'},
 box:{title:'Box Joint',base:'box',desc:'Sambungan jejari berselang-seli yang menghasilkan permukaan cantuman luas.',outcome:'Memahami susunan jejari dan kaedah pemasangan box joint.',app:'Kotak, laci dan projek kerja kayu kecil.',adv:'Mudah difahami, kemas dan stabil.'},
 lap:{title:'Lap Joint',base:'lap',desc:'Sambungan bertindih yang mengurangkan sebahagian ketebalan kayu untuk dicantum rata.',outcome:'Memahami konsep pertindihan dan aras permukaan kayu.',app:'Rangka ringan, bingkai dan struktur sokongan.',adv:'Ringkas, cepat dibuat dan sesuai untuk pembelajaran asas.'},
 finger:{title:'Finger Joint',base:'tongue',desc:'Sambungan jari yang meningkatkan kawasan sentuhan untuk sambungan yang lebih kuat.',outcome:'Mengenal pasti bentuk jari dan fungsi pelekat pada sambungan.',app:'Papan cantum, komponen panjang dan kerja perabot.',adv:'Menjimatkan bahan dan membantu menghasilkan sambungan panjang.'},
 miter:{title:'Mitre Joint',base:'miter',desc:'Sambungan bersudut 45 darjah yang menghasilkan penjuru kemas dan menarik.',outcome:'Memahami sudut potongan dan padanan penjuru.',app:'Bingkai gambar, kemasan hiasan dan penjuru perabot.',adv:'Estetik, kemas dan sesuai untuk kemasan luaran.'},
 cross:{title:'Three-Way Cross Joint',base:'cross',desc:'Sambungan tiga arah yang menggabungkan beberapa komponen pada satu titik pusat.',outcome:'Memahami orientasi komponen dalam sambungan tiga arah.',app:'Struktur rangka, sokongan bersilang dan model pembelajaran.',adv:'Menunjukkan hubungan spatial yang jelas dan mencabar.'}
};
let currentModel='mortise';let currentStep=1;
function updateViewer(){const viewer=document.getElementById('mainViewer');if(!viewer)return;const item=modelData[currentModel];viewer.src=`models/${item.base}_step${currentStep}.glb`;document.getElementById('currentStepText').textContent=`Step ${currentStep}`;document.getElementById('jointTitle').textContent=item.title;document.getElementById('jointDesc').textContent=item.desc;document.getElementById('jointOutcome').textContent=item.outcome;document.getElementById('jointApp').textContent=item.app;document.getElementById('jointAdv').textContent=item.adv;}
document.querySelectorAll('.joint-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.joint-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentModel=btn.dataset.model;currentStep=1;document.querySelectorAll('.step-btn').forEach(b=>b.classList.remove('active'));document.querySelector('.step-btn[data-step="1"]')?.classList.add('active');updateViewer()}));
document.querySelectorAll('.step-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.step-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentStep=Number(btn.dataset.step);updateViewer()}));
document.getElementById('autoRotateToggle')?.addEventListener('change',e=>{const viewer=document.getElementById('mainViewer');if(e.target.checked)viewer.setAttribute('auto-rotate','');else viewer.removeAttribute('auto-rotate')});
const params=new URLSearchParams(location.search);const chosen=params.get('model');if(chosen&&modelData[chosen]){currentModel=chosen;document.querySelectorAll('.joint-btn').forEach(b=>b.classList.toggle('active',b.dataset.model===chosen));updateViewer()}
document.querySelectorAll('.quiz-open').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.quiz-frame').forEach(f=>f.classList.remove('active'));document.getElementById(btn.dataset.target)?.classList.add('active');document.querySelector('.quiz-frame-wrap')?.scrollIntoView({behavior:'smooth',block:'start'})}));
