const modelData=[
{key:'mortise',title:'Mortise & Tenon Joint',short:'Mortise & Tenon',img:'images/mortise.png',desc:'Sambungan lidah dan lubang yang kuat dan stabil, sesuai untuk struktur rangka dan perabot tahan lama.',learn:'Memahami struktur lidah dan lubang serta cara pemasangan tanggam.',apply:'Perabot, rangka pintu, tingkap dan struktur binaan.',adv:'Kukuh, stabil dan tahan lama.'},
{key:'dovetail',title:'Dovetail Joint',short:'Dovetail Joint',img:'images/dovetail.png',desc:'Tanggam berbentuk ekor merpati yang terkenal dengan kekuatan tarikan dan nilai estetika.',learn:'Mengenal pasti bentuk kunci dovetail dan arah pemasangannya.',apply:'Laci, kotak kayu dan kabinet.',adv:'Kuat, kemas dan menarik.'},
{key:'box',title:'Box Joint',short:'Box Joint',img:'images/box.png',desc:'Sambungan jejari berselang-seli yang menghasilkan kawasan lekatan luas.',learn:'Memahami sambungan jejari berselang dan fungsi permukaan gam.',apply:'Kotak, laci dan panel kayu.',adv:'Mudah dibuat, kukuh dan kemas.'},
{key:'lap',title:'Lap Joint',short:'Lap Joint',img:'images/lap.png',desc:'Dua komponen kayu bertindih separuh untuk menghasilkan sambungan rata.',learn:'Memahami konsep pertindihan separuh kayu.',apply:'Rangka, bingkai dan struktur ringan.',adv:'Ringkas, cepat dan stabil.'},
{key:'tongue',title:'Finger Joint',short:'Finger Joint',img:'images/tounge.png',desc:'Sambungan jejari yang meningkatkan kawasan lekatan serta kekuatan kayu.',learn:'Mengenal bentuk jejari dan arah cantuman.',apply:'Penyambungan kayu panjang dan panel.',adv:'Menjimatkan bahan dan kukuh.'},
{key:'miter',title:'Mitre Joint',short:'Mitre Joint',img:'images/miter.png',desc:'Sambungan sudut 45 darjah yang memberi kemasan bersih dan profesional.',learn:'Memahami sudut potongan mitre.',apply:'Bingkai gambar, trim dan perabot hiasan.',adv:'Kemas dan estetik.'},
{key:'cross',title:'Three-Way Cross Joint',short:'Three-Way Cross Joint',img:'images/cross.png',desc:'Sambungan tiga arah yang menunjukkan hubungan spatial kayu secara kompleks.',learn:'Memahami penyambungan tiga arah dalam ruang 3D.',apply:'Struktur kreatif dan latihan visualisasi spatial.',adv:'Meningkatkan kefahaman ruang.'}
];
const $=s=>document.querySelector(s);
$('.menuBtn')?.addEventListener('click',()=>$('.links')?.classList.toggle('open'));
const io=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting)x.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.fade').forEach(el=>io.observe(el));
const strip=$('#modelStrip');if(strip){modelData.forEach((m,i)=>strip.innerHTML+=`<article><img src="${m.img}" alt="${m.short}"><small>0${i+1}</small><b>${m.short}</b></article>`)}
let current=0,step=1;function glb(key,n){return`models/${key}_step${n}.glb`}
function updateViewer(){const m=modelData[current],viewer=$('#viewer');if(!viewer)return;viewer.src=glb(m.key,step);$('#modelTitle').textContent=m.title;$('#modelDesc').textContent=m.desc;$('#learn').textContent=m.learn;$('#apply').textContent=m.apply;$('#adv').textContent=m.adv;document.querySelectorAll('#modelList button').forEach((b,i)=>b.classList.toggle('active',i===current));document.querySelectorAll('.steps button').forEach((b,i)=>b.classList.toggle('active',i+1===step));const thumbs=$('#thumbs');if(thumbs){thumbs.innerHTML='';for(let i=1;i<=4;i++)thumbs.innerHTML+=`<img src="${m.img}" alt="${m.short} Step ${i}" onclick="setStep(${i})">`}}
function setModel(i){current=i;step=1;updateViewer()}function setStep(n){step=n;updateViewer()}window.setStep=setStep;
const list=$('#modelList');if(list){modelData.forEach((m,i)=>{const b=document.createElement('button');b.textContent=`0${i+1}  ${m.short}`;b.onclick=()=>setModel(i);list.appendChild(b)});for(let i=1;i<=4;i++)$('.steps').innerHTML+=`<button onclick="setStep(${i})">Step ${i}</button>`;updateViewer();$('#autoRotate')?.addEventListener('change',e=>{e.target.checked?$('#viewer').setAttribute('auto-rotate',''):$('#viewer').removeAttribute('auto-rotate')})}
document.querySelectorAll('[data-quiz]').forEach(btn=>btn.addEventListener('click',()=>{const frame=btn.closest('.quizCard').querySelector('.quizFrame');frame.classList.toggle('open');btn.textContent=frame.classList.contains('open')?'Tutup Kuiz':'Mula Kuiz'}));
